period/models.py
from . import db

class Use(db.Model):
    __tablename__ = 'uses'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'defaultuse.jpg')
    items = db.relationship('Item', backref='Use', cascade="all, delete-orphan")

    def __repr__(self):
        return f"ID: {self.id}\nName: {self.name}\nDescription: {self.description}"

orderdetails = db.Table('orderdetails', 
    db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('item_id',db.Integer,db.ForeignKey('items.id'),nullable=False),
    db.PrimaryKeyConstraint('order_id', 'item_id') )

class Item(db.Model):
    __tablename__ = 'items'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64),nullable=False)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False)
    price = db.Column(db.Float, nullable=False)
    use_id = db.Column(db.Integer, db.ForeignKey('uses.id'))
    
    def __repr__(self):
        return f"ID: {self.id}\nName: {self.name}\nDescription: {self.description}\nPrice: {self.price}\nUse: {self.use_id}"

class Order(db.Model):
    __tablename__ = 'orders'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    firstname = db.Column(db.String(64))
    surname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    totalcost = db.Column(db.Float)
    date = db.Column(db.DateTime)
    items = db.relationship("Item", secondary=orderdetails, backref="orders")

    def __repr__(self):
        return f"ID: {self.id}\nStatus: {self.status}\nFirst Name: {self.firstname}\nSurname: {self.surname}\nEmail: {self.email}\nPhone: {self.phone}\nDate: {self.date}\nItems: {self.items}\nTotal Cost: ${self.totalcost}"

period/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired, email

# form used in basket
class CheckoutForm(FlaskForm):
    firstname = StringField("Your first name", validators=[InputRequired()])
    surname = StringField("Your surname", validators=[InputRequired()])
    email = StringField("Your email", validators=[InputRequired(), email()])
    phone = StringField("Your phone number", validators=[InputRequired()])
    submit = SubmitField("Checkout")

period/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap4
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

#create a function that creates a web application
# a web server will run this web application
def create_app():
    app = Flask(__name__)
    # Don't leave this enabled in production
    app.debug = True
    
    app.secret_key = 'BetterSecretNeeded123'

    #set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///periods.sqlite'

    # initialise db with flask app - necessary because scope of app
    # is only here in create_app, but db is defined globally
    db.init_app(app)
    
    Bootstrap4(app)
    
    #importing modules here to avoid circular references, register blueprints of routes
    from . import views
    app.register_blueprint(views.main_bp)
    #from . import admin
    #app.register_blueprint(admin.admin_bp)
    
    @app.errorhandler(404) 
    # Inbuilt function (to Flask) which takes error as parameter
    def not_found(e): 
      return render_template("error.html", error=e)

    # Handles server errors (look-up 'HTTP response status codes')
    @app.errorhandler(500)
    def internal_error(e):
      return render_template("error.html", error=e)
   
    return app

period/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Use, Item, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db

main_bp = Blueprint('main', __name__)

# Home page
@main_bp.route('/')
def index():
    items = db.session.scalars(db.select(Item).order_by(Item.id)).all()
    uses = db.session.scalars(db.select(Use).order_by(Use.id)).all()
    return render_template('index.html', items = items, uses = uses)

# View item details
@main_bp.route('/itemdetail/<int:item_id>')
def itemdetail(item_id):
    item = db.session.scalars(db.select(Item).where(Item.id==item_id)).first()
    return render_template('itemdetail.html', item=item)

# View all the items of a use
@main_bp.route('/uses/<int:use_id>')
def useitems(use_id):
    items = db.session.scalars(db.select(Item).where(Item.use_id==use_id)).all()
    return render_template('useitems.html', items=items)


# Search
@main_bp.route('/items/')
def search():
    search = request.args.get('search')
    search = '%{}%'. format(search)
    items = Item.query.filter(Item.description.like(search)).all()
    return render_template('useitems.html', items = items)




# Referred to as "Basket" to the user
@main_bp.route('/order', methods=['POST', 'GET'])
def order():
    item_id = request.args.get('item_id')    #args 대신 values?
    # retrieve order if there is one
    if 'order_id' in session.keys():
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        # order will be None if order_id/session is stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status=False, firstname='', surname='', email='', phone='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except Exception as e:
            print(f'Failed at creating a new order: {str(e)}')
            order = None
    
    # calculate total price
    totalprice = 0
    if order is not None:
        for item in order.items:
            totalprice += item.price
    
    # are we adding an item?
    if item_id is not None and order is not None:
        item = db.session.scalar(db.select(Item).where(Item.id==item_id))
        if item not in order.items:
            try:
                order.items.append(item)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('This item is already in the basket')
            return redirect(url_for('main.order'))
    return render_template('order.html', order=order, totalprice=totalprice)

# Delete specific basket items
# Note this route cannot accept GET requests now
@main_bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = db.get_or_404(Order, session['order_id'])
        item_to_delete = db.session.scalar(db.select(Item).where(Item.id==id))
        try:
            order.items.remove(item_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# Scrap basket
@main_bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items are deleted')
    return redirect(url_for('main.index'))

# Complete the order
@main_bp.route('/checkout', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = db.get_or_404(Order, session['order_id'])
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            totalcost = 0
            for item in order.items:
                totalcost += item.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you! Your order has been successfully delivered!')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form)

period/templates/base.html
<!doctype html>
<html lang="en">

<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="../static/css/index.css">
<title>Period.</title>
</head>

<body>
    <section class="header">
        <div class="header-inner">
            <div class="container">
                <div class="mainMenu">
                    <div class="logo">
                    <h1><a href="{{url_for('main.index')}}">Period.</a></h1>
                    </div>
                    <div class="container-fluid">
                        <div class="navbar_main">
                        <div class="row">
                            <div class="col-xs-12 col-md-8 lg-8">
                                <nav class="navbar navbar-custom bg-light">
                                    <a class="navbar-brand" href="{{url_for('main.index')}}">Shop all</a>
                                    <a class="navbar-items" href="{{url_for('main.useitems', use_id=1)}}">Single-Use</a>
                                    <a class="navbar-items" href="{{url_for('main.useitems', use_id=2)}}">Multi-Use</a>
                                    <a class="navbar-items" href="{{url_for('main.index')}}">Subscribe</a>
                                    <a class="navbar-items" href="{{url_for('main.index')}}">Learn</a>
                                </nav>
                            </div>
                            <div class="col-xs-6 col-md-4 lg-4">
                                <div class="user">
                                    <div class="login">
                                        <a href="#none">
                                        <img src="../static/img/img_logo.png" alt="login" width="25" height="25">
                                        </a>
                                    </div>
                                    <div class="cart">
                                        <a href="{{url_for('main.order')}}">
                                        <img src="../static/img/img_cart.png" alt="cart" width="25" height="25">
                                        </a>
                                    </div>
                                    <div class="search">
                                        <form class="form-flex" action="{{url_for('main.search')}}">
                                            <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search">
                                            <button class="btn btn-outline-danger btn-s"
                                                type="submit">Search</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>                    
            </div>
        </div>

    </section>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="alert alert-danger" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        </div>
    {% endif %}
    {% endwith %} 

    {% block head %}
            
    {% endblock %}

    <!-- main page content goes in container -->
    <div class="container-fluid">
        <main>
            {% block main %}
            
            {% endblock %}
        </main>
    </div>
    
    <!-- subscription -->
    <div class="jumbotron">
        <h3>Why Subscribe?</h3>
        <p class="lead">Save on Every Order
            Get your must-haves at 10% off + earn 2x the rewards points! And don’t forget free shipping on orders over $50+.</p>
        <hr class="my-2">
        <p>With a subscription, you’ll never have to make a last minute trip to the store again.</p>
        <p class="lead">

            <ul class="list-group">
                <li class="list-group-item"><span id="Step">Step1 ☝️</span> <br> Choose one or more products. Wide range of colours and sizes.</li>
                <li class="list-group-item"><span id="Step">Step2 ✌️</span> <br> Choose how frequently you want your products to be delivered.</li>
                <li class="list-group-item"><span id="Step">Step3 </span> <br> Update your subscription at anytime.</li>
              </ul>
              <br>
          <a class="btn btn-danger btn-lg" href="#!" role="button">Subscribe</a>
        </p>
      </div>
      

      



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>




</body>

<footer>

    <div class="footer__menu">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 col-md-4 col-lg-4">
                    <h4>Shop</h4>
                    <nav class="navbar">
                        <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">All Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Single-Use</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Multi-Use</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Subscribe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Find a store</a>
                        </li>
                        </ul>
                    </nav>
                    <br>
                </div>

                <div class="col-sm-6 col-md-4 col-lg-4">
                    <h4>Company</h4>
                    <nav class="navbar">
                        <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Our Story</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Wholesale</a>
                        </li>
                        </ul>
                    </nav>
                    <br>
                </div>

                <div class="col-sm-4 col-md-4 col-lg-4">
                    <h4>Support</h4>
                    <nav class="navbar">
                        <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">FAQs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Orders & Shipping</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Returns & Refunds</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact Us</a>
                        </li>
                        </ul>
                    </nav>
                    <br>
                </div>
            </div>
        </div>
    </div>

</footer>
</html>

   

period/templates/checkout.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block head %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="alert alert-danger" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        </div>
    {% endif %}
    {% endwith %} 
{% endblock %}

{% block main %}
    <section>
        <div class="checkout__form">
            <div class="container">
                <div class="row">
                    <div class = "col-12">
                        <h2>Checkout</h2>
                        <p>
                            Thank you for your interest. <br> Please provide your details so that one of our awesome tour agents can contact you to finalise details and take payment.
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class = "col-6">
                        {{ render_form(form) }}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

period/templates/error.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <h1>Error</h1>
    <p>Sorry, but something went wrong!</p>
    <p>More info: {{error}}</p>
</div>
{% endblock %}

period/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!-- main banner -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block w-100" src="../static/img/img_01.jpg" alt="main_banner_img_01" width="100%" height="100%">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="../static/img/img_01.jpg" alt="main_banner_img_01" width="100%" height="100%">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
{% endblock %}

{% block main %}
 <!-- all products_main --> 

  <section>

    <div class="container-fluid">
        <div>
          <p class="main_products" id="uses_anchor"> <h2>Shop all</h2></p>
        </div>

      <div class="card-columns">
          <!-- each tour is a bootstrap card -->
          {% for item in items%}
          <div class="main__items">
          <div class="card">
              <img class="card-img-top" src="{{url_for('static', filename='img/'+item.image)}}" alt="Card image">
              <div class="card-body">
                  <h4 class="card-title">{{item.name}}</h4>
                  <!-- <p class="card-text">{{item.description}}</p> -->
              </div>
              <div class="card-footer">
                <form action="{{url_for('main.itemdetail', item_id=item.id)}}">
                  <input type="hidden" id="item_id" name="item_id" value="{{item.id}}">
                  <input class="btn btn-danger" type="submit" value="View detail">
              </form>
              <form action="{{url_for('main.order')}}">
                  <input type="hidden" id="item_id" name="item_id" value="{{item.id}}">
                  <input class="btn btn-danger" type="submit" value="Add to Cart">
              </form>
              </div>
          </div>
          </div>
          {% endfor %}
      </div>
    </div>

  </section>

  
  <section>
    <div class="container-fluid">
        <div>
            <p class="main_products" id="uses_anchor"><h2>Our Range</h2></p>
        </div>
    <div class="card-deck">

        {% for use in uses %}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+use.image)}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{use.name}}</h4>
                <p class="card-text">{{use.description}}</p>
            </div>
            <div class="card-footer"><a href= "{{url_for('main.useitems', use_id=use.id)}}" class="btn btn-danger">Learn More</a></div>
        </div>
        {% endfor %}
    </div>
    </div>
</section>



{% endblock %}

period/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>  
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h3>Shopping Cart</h3>
        </div>
        <!-- each tour on seperate row -->
        {% for item in order.items %}
            <div class="row shadow-md my-row mb-3">
                <div class="col-sm-10 card">
                    <h5 class="card-header">{{item.Use.name}} {{item.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + item.image))}}">
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->
                                <p class="card-text">{{item.description}}</p>   
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                    <!-- delete item button -->
                        <h5>{{"$%.2f"|format(item.price)}}</h5>
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="{{item.id}}">
                            <input type="submit" value="Delete" class="btn btn-danger mb-3">
                        </form> 
                </div>
            </div>
        {% endfor %}
        
        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4">Total = {{"$%.2f"|format(totalprice)}}</h5>
            </div>
        
            <div class="checkout__btn">
            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{url_for('main.index', _anchor='uses_anchor')}}" class="btn btn-danger mr-4">View Items</a>
                <a href="{{url_for('main.checkout')}}" class="btn btn-danger mr-4">Checkout</a>
                <a href="{{url_for('main.deleteorder')}}" class="btn btn-danger">Delete All</a>
            </div>
            </div>
        </section>
    </div>
</section>
{% endblock %}

period/templates/useitems.html
{% extends 'base.html' %}

{% block main %}
<section>

    <div class="text-dark text-center">
        <div>
            <p class="lead"><h4>For your better period</h4></p>
        </div>
    </div>

    <div class="useitems">
    <div class="card-columns">
        <!-- each tour is a bootstrap card -->
        {% for item in items%}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+item.image)}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{item.name}}</h4>
                <p class="card-text">{{item.description}}</p>
            </div>
            <div class="card-footer">
                <form action="{{url_for('main.itemdetail', item_id=item.id)}}">
                    <input type="hidden" id="item_id" name="item_id" value="{{item.id}}">
                    <input class="btn btn-danger" type="submit" value="View detail">
                </form>
                <form action="{{url_for('main.order')}}">
                    <input type="hidden" id="item_id" name="item_id" value="{{item.id}}">
                    <input class="btn btn-danger" type="submit" value="Add to Cart">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>

</section>
{% endblock %}